### ISSUE TITLE
Add merge into main protection/check

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/clim-recal#31]
See note on slack from Ruth - thank you!!!

**Comment by RuthBowyer** [comment]
Here is the note from slack for easy reference (sorry again!) 

> I'm really sorry - not sure if you saw my comment but whilst trying to push some files on to a new branch so I could PR, I seemingly merged it to main - I think I was using git checkout incorrectly! :see_no_evil: Anyway I was googling to try and fix today and I used `git reset --hard 733854c` for the 'bad' commit, but because the console message suggested:
 `HEAD is now at 733854c Files to process raster data to df` 
This commit from rebranching of DataProcessingR so I thought I needed to go one more commit back and did `git reset --hard HEAD~1` - but this suggests:
`HEAD is now at 800976b Merge pull request #29 from alan-turing-institute/InterimRuns` - which I think is too far back (but could be because the branch I'm working on was not merged with your readme changes?)
> Anyway I haven't pushed incase I'm going to mess things up further by doing so - So sorry about this!
