### ISSUE TITLE
Bias Correction of UK wide data for LCAT

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/clim-recal#33]
For one of our stakeholders, we need to provide them BC for whole of UK data by the end of September.
- MVP: Deliver 1 run tasmax, tasmin, precip, including the historical model
- Stretch Goal: Deliver 4 runs (Run 5, 6, 7, 8)

Additional Info:
- It has been agreed that we will decide the BC method, likely Empirical Quantile Mapping (to confirm this method name) 
- Ruth has been running this in `R` using `qmap` and it's going well so far - currently looping over the whole of the UK. 
When this has been processed, the following steps will be needed:

Tasks:
- [ ] Sense checking code and outputs and assessing the data

**Comment by RuthBowyer** [comment]
Adding here for further discussion - I realised I've made a slight error which unfortunately I think means re-running several steps with a different input shapefile...

I used this shapefile to crop all of the rasters to convert to dataframe and then apply the bias correction: 


![Image](https://github.com/alan-turing-institute/clim-recal/assets/105492883/c8ee5627-a4b0-406c-84e5-5aa1791c3160)

Because I was masking the raster (ie using the lines to crop the raster, rather than using the full (square) extent as we will for the 3 cities) with the shape, it crops out everything not within this raster.

However, what I noticed last week but have only just realised will be an issue - is that this means that areas where the majority of the grid cell is a *river or estuary* the cells also get dropped, see this London example: 


![Image](https://github.com/alan-turing-institute/clim-recal/assets/105492883/7adb75c6-6f0d-4f52-bb17-97cf143803e8)


This is generally not a big deal apart from I've realised that LCAT give the option of sharing this data at LSOA level. In some dense areas (eg London) this could mean some areas will return NA values because of this (ie where the area is made up only of this riverbank areas) 

There will be very very few LSOAs effects I believe, **but** there is a really easy fix, which is to just use a different shapefile and process everything again (i would suggest using [this one](https://www.ukpostcode.net/shapefile-of-uk-administrative-counties-wiki-16.html) - handily linked in LCAT docs, or I can find another one/use a few! 

Apologies!

**Comment by RuthBowyer** [comment]
Note too: I need to re-run the year alignment I believe, because the CPM actually starts in Dec 1980, not Jan 1980

**Comment by RuthBowyer** [comment]
OK just to confirm, there are NA cells in the HADs grid that are causing the NA cells above in the bias corrected CPM. See this example which is cropped using the London extent (ie not the shapefile I've overlaid for illustrative purposes!) - the raster is the first layer of `Raw/HadsUKgrid/tasmax/day/tasmax_hadukgrid_uk_1km_day_19800101-19800131.nc` 

![image](https://github.com/alan-turing-institute/clim-recal/assets/105492883/15ef0c36-c467-4042-9be0-154752bfaae8)


Unless it's easy during the resampling for 360 days to interpolate these values (@aranas welcome your thoughts!) then I think best to just accept the NA.

However, I do still need to run this, as indeed I completely forgot to account for this: 
> Note too: I need to re-run the year alignment I believe, because the CPM actually starts in Dec 1980, not Jan 1980

This is more of an error than the missing NAs as the values are shifted by a month and so we can't use this for BC data, so I will re-run once the HADs has been sampled to 360 days. (Fortunately it will be just a few lines of code adjustment for the new data and then just babysitting!)

**Comment by gmingas** [comment]
Closing this and Ruth to add assessment and sense checking outstanding tasks to #39

**Comment by RuthBowyer** [comment]
Just for future reference: I re-ran this to accommodate the update as mentioned: 

> Note too: I need to re-run the year alignment I believe, because the CPM actually starts in Dec 1980, not Jan 1980
